# Generated by Django 3.0.3 on 2020-03-28 08:44
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_courses_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='cours.Courses'),
        ),
    ]
