# Generated by Django 3.0.5 on 2020-04-24 22:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_auto_20200328_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
